.pragma library

var TRANSACTION_TYPES = [];
TRANSACTION_TYPES["INTEREST_DIVIDENDS"] = qsTr("Interest / Dividends");
TRANSACTION_TYPES["SECURITIES"] = qsTr("Securities");
TRANSACTION_TYPES["MISCELLANEOUS"] = qsTr("Miscellaneous");
TRANSACTION_TYPES["TRANSFER"] = qsTr("Transfer");

var DEBTOR_CREDITOR_TRANSACTION = ["TRANSFER", "MISCELLANEOUS"];

