.pragma library

var TRANSACTION_TYPES = [];
TRANSACTION_TYPES["INTEREST_DIVIDENDS"] = qsTr("Interest / Dividends");
TRANSACTION_TYPES["SECURITIES"] = qsTr("Securities");
TRANSACTION_TYPES["SAVINGS"] = qsTr("Savings");
TRANSACTION_TYPES["MISCELLANEOUS"] = qsTr("Miscellaneous");
TRANSACTION_TYPES["TRANSFER"] = qsTr("Transfer");
TRANSACTION_TYPES["UNKNOWN"] = qsTr("Unknown");
TRANSACTION_TYPES["CANCELLATION"] = qsTr("Cancellation");
TRANSACTION_TYPES["DIRECT_DEBIT"] = qsTr("Direct Debit");
TRANSACTION_TYPES["ATM_WITHDRAWAL"] = qsTr("ATM Withdrawal");
TRANSACTION_TYPES["CARD_TRANSACTION"] = qsTr("Card Transaction");

var DEBTOR_CREDITOR_TRANSACTION = ["TRANSFER", "MISCELLANEOUS"];

